M48
; DRILL file {KiCad 9.0.8-1.fc43} date 2026-04-27T11:30:58+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-04-27T11:30:58+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8-1.fc43
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X4.773Y-3.9309
X5.0006Y-3.9309
T2
X4.027Y-3.8445
X4.477Y-3.8445
M30
